name: "HA Audit"
version: "0.6.7"
slug: "ha_audit"
description: "Read-only Home Assistant health and configuration auditor"

arch:
  - amd64

startup: once
boot: manual_only
init: false

hassio_api: true
homeassistant_api: true
hassio_role: default

map:
  - type: addon_config
    read_only: false

  - type: homeassistant_config
    read_only: true

options: {}
schema: {}
